name: Cleanup Docs Preview

on:
  pull_request_target:
    types: [closed]

jobs:
  cleanup:
    name: Cleanup PR Preview
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Deactivate GitHub deployment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ github.token }}
          environment: "Docs Preview (PR #${{ github.event.pull_request.number }})"
          onlyDeactivateDeployments: true
